name: Build and Deploy

on:
  workflow_call:
    inputs:
      MPKIT_URL:
        description: 'MPKIT URL'
        required: true
        default: ''
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      MPKIT_EMAIL: ${{ secrets.MPKIT_EMAIL }}
      MPKIT_TOKEN: ${{ secrets.MPKIT_TOKEN }}
      MPKIT_URL: ${{ needs.reserve-ci-instance.outputs.mpkit-url }}
      CI: false
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      DEBUG: 1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            front_app/node_modules
          key: cache-node-modules-${{ hashFiles('front_app/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm run install:ci

      - name: Set SHA
        run: |
          echo "::set-env name=FRONT_APP_SHA::$( git rev-list -1 HEAD -- front_app )"
        shell: bash

      - name: Cache front_app Assets
        id: cache-front_app-assets
        uses: actions/cache@v2
        with:
          path: |
            app/assets/app
            app/views/layouts/app.liquid
          key: ${{env.MPKIT_URL}}-front_app-assets-${{ env.FRONT_APP_SHA }}

      - name: Build front_app
        if: steps.cache-front_app-assets.outputs.cache-hit != 'true'
        env:
          PUBLIC_URL: "${{ env.MPKIT_URL}}/assets/app/"
          REACT_APP_API_URL: "${{env.MPKIT_URL}}/api"
        shell: sh
        run: |
          echo "-----------------------------------------"
          echo $PUBLIC_URL
          echo $REACT_APP_API_URL
          echo "-----------------------------------------"
          npm run --prefix front_app build

      - name: Deploy
        env:
          CI: true
        shell: sh
        run: |
          set -e
          unset DEBUG
          npm -g install @platformos/pos-cli

          sh ./tests/seed.sh
