name: Build and Deploy to Test Environment
on:
  workflow_call:
    inputs:
      deployment-type:
        required: true
        type: string
        description: "Deployment type: 'frontapp' (front_app only) or 'full' (all apps)"
      ci-env:
        required: true
        type: boolean
      mpkit-url:
        required: true
        type: string
    secrets:
      mpkit-email:
        required: true
      mpkit-token:
        required: true
      paymentus-secret-key:
        required: true

jobs:
  deploy-frontapp:
    if: inputs.deployment-type == 'frontapp'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      MPKIT_EMAIL: ${{ secrets.mpkit-email }}
      MPKIT_TOKEN: ${{ secrets.mpkit-token }}
      MPKIT_URL: ${{ inputs.mpkit-url }}
      PAYMENTUS_SECRET_KEY: ${{ secrets.paymentus-secret-key }}
      CI: ${{ inputs.ci-env }}
      DEBUG: 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            front_app/node_modules
          key: cache-node-modules-${{ hashFiles('front_app/package-lock.json') }}

      - name: Install Dependencies
        run: npm run install:ci

      - name: Set SHA
        run: |
          echo "FRONT_APP_SHA=$(git rev-list -1 HEAD -- front_app)" >> "$GITHUB_ENV"
        shell: bash

      - name: Cache front_app Assets
        id: cache-front_app-assets
        uses: actions/cache@v4
        with:
          path: |
            app/assets/app
            app/views/layouts/app.liquid
          key: ${{ env.MPKIT_URL }}-front_app-assets-${{ env.FRONT_APP_SHA }}

      - name: Build front_app
        env:
          PUBLIC_URL: "${{ env.MPKIT_URL}}/assets/app/"
          REACT_APP_API_URL: "${{ env.MPKIT_URL }}/api"
        shell: sh
        run: |
          echo "-----------------------------------------"
          echo $PUBLIC_URL
          echo $REACT_APP_API_URL
          echo "-----------------------------------------"
          npm run --prefix front_app build

      - name: Deploy
        shell: sh
        run: |
          set -e
          unset DEBUG
          echo "Installing PlatformOS CLI..."
          npm -g install @platformos/pos-cli
          echo "Running deployment seed script..."
          sh ./tests/seed.sh
          echo "Deployment completed successfully"

  deploy-full:
    if: inputs.deployment-type == 'full'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      MPKIT_EMAIL: ${{ secrets.mpkit-email }}
      MPKIT_TOKEN: ${{ secrets.mpkit-token }}
      MPKIT_URL: ${{ inputs.mpkit-url }}
      PAYMENTUS_SECRET_KEY: ${{ secrets.paymentus-secret-key }}
      CI: false
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      DEBUG: 1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            src_app/node_modules
            tests/node_modules
            src_site/node_modules
            modules/admin/react-app/node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json', 'tests/package-lock.json', 'src_app/package-lock.json', 'src_site/package-lock.json', 'modules/admin/react-app/package-lock.json') }}

      - name: Install Dependencies
        run: npm run install:ci

      - name: Set Environment Variables
        run: |
          echo "INSTANCE_DOMAIN=${MPKIT_URL/https:\/\//}" >> $GITHUB_ENV
        shell: bash

      - name: Set SHA (src_app)
        run: |
          echo "SRC_APP_SHA=$(git rev-list -1 HEAD -- src_app)" >> $GITHUB_ENV
        shell: bash

      - name: Cache src_app Assets
        id: cache-src_app-assets
        uses: actions/cache@v4
        with:
          path: |
            app/assets/app
            app/views/layouts/app.liquid
          key: ${{ env.INSTANCE_DOMAIN }}-src-app-assets-${{ env.SRC_APP_SHA }}

      - name: Build src_app
        env:
          PUBLIC_URL: "${{ env.MPKIT_URL}}/assets/app/"
          REACT_APP_API_URL: "${{ env.MPKIT_URL }}/api"
        shell: sh
        run: |
          echo "-----------------------------------------"
          echo $PUBLIC_URL
          echo $REACT_APP_API_URL
          echo "-----------------------------------------"
          npm run --prefix src_app build

      - name: Set SHA (src_site)
        run: |
          echo "SRC_SITE_SHA=$(git rev-list -1 HEAD -- src_site)" >> $GITHUB_ENV
        shell: bash

      - name: Cache src_site Assets
        id: cache-src_site-assets
        uses: actions/cache@v4
        with:
          path: |
            app/assets/site
            app/views/partials/layout/assets.liquid
          key: src_site-assets-1-${{ env.SRC_SITE_SHA }}

      - name: Build src_site
        shell: sh
        run: npm run build:site

      - name: Set SHA (admin)
        run: |
          echo "ADMIN_SHA=$(git rev-list -1 HEAD -- modules/admin/react-app)" >> $GITHUB_ENV
        shell: bash

      - name: Cache admin Assets
        id: cache-admin-assets
        uses: actions/cache@v4
        with:
          path: |
            modules/admin/public/assets
            modules/admin/public/views/layouts/index.liquid
          key: ${{ env.INSTANCE_DOMAIN }}-admin-assets-${{ env.ADMIN_SHA }}

      - name: Build Admin
        env:
          PUBLIC_URL: "${{ env.MPKIT_URL}}/assets/modules/admin/"
          REACT_APP_API_URL: ${{ env.MPKIT_URL }}/admin-api
        shell: sh
        run: |
          set -e
          echo "-----------------------------------------"
          echo $PUBLIC_URL
          echo $REACT_APP_API_URL
          echo "-----------------------------------------"
          npm run --prefix modules/admin build:ci

      - name: Deploy
        env:
          CI: true
        shell: sh
        run: |
          set -e
          unset DEBUG
          echo "Installing PlatformOS CLI..."
          npm -g install @platformos/pos-cli
          echo "Running deployment seed script..."
          sh ./tests/seed.sh
          echo "Deployment completed successfully"
