name: Run ZAP Automation Plan with Dev CICD Policy
on:
  workflow_call:
    inputs:
      MPKIT_URL:
        required: true
        type: string
      PLAN:
        required: true
        type: string
    secrets:
      E2E_TEST_PASSWORD:
        required: true
      POS_CI_PS_REPO_ACCESS_TOKEN:
        required: false
      MPKIT_TOKEN:
        required: false

jobs:
  zap-dast:
    runs-on: ubuntu-latest
    env:
      CI: true
      E2E_TEST_PASSWORD: ${{ secrets.E2E_TEST_PASSWORD }}
      MPKIT_TOKEN: ${{ secrets.MPKIT_TOKEN }}
      MPKIT_URL: ${{ inputs.MPKIT_URL }}
      POS_CI_PS_REPO_ACCESS_TOKEN: ${{ secrets.POS_CI_PS_REPO_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change permissions for zap directory
        run: chmod -R 777 zap

      - name: Run ZAP Dev CICD Automation Plan
        id: run_plan
        uses: zaproxy/action-af@v0.2.0
        with:
          plan: ${{ inputs.PLAN }}
          docker_env_vars: |
            E2E_TEST_PASSWORD=${{ env.E2E_TEST_PASSWORD }}
            MPKIT_URL=${{ env.MPKIT_URL }}

      - name: Check if ZAP Scan report has been generated
        id: check_report
        run: |
          if [ ! -f zap/*.md ]; then
            echo "ZAP Scan report not found. Skipping summary and upload."
            echo "report=false" >> $GITHUB_OUTPUT
          else
            echo "ZAP Scan report found."
            echo "report=true" >> $GITHUB_OUTPUT
          fi

      - name: Show ZAP Scan Report in the summary
        id: show_summary
        if: always() && steps.run_plan.outcome != 'skipped' && steps.check_report.outputs.report == 'true'
        run: |
          echo "# ZAP Dev CICD Automation Plan Summary :checkered_flag:" >> $GITHUB_STEP_SUMMARY
          echo "## Result: ${{ steps.run_plan.outcome }} ${{ env.RESULT_ICON }}" >> $GITHUB_STEP_SUMMARY
          cat zap/*.md >> $GITHUB_STEP_SUMMARY
        env:
          RESULT_ICON: ${{ steps.run_plan.outcome == 'success' && ':white_check_mark:' || ':x:' }}

      - name: Upload ZAP Scan Report
        if: steps.check_report.outputs.report == 'true' && steps.show_summary.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: zap_scan
          path: |
            zap/*/
            zap/*.md
            zap/*.html
