name: Run platformos-check on Liquid files

on:
  workflow_call:
    inputs:
      docker_workspace:
        description: 'Directory to scan (defaults to repository root)'
        required: false
        default: ${{ github.workspace }}
        type: string

env:
  CI: true
  PLATFORMOS_CHECK_DEBUG: true
  DOCKER_WORKSPACE: ${{ inputs.docker_workspace }}
  LOGS_DIR: logs

jobs:
  run-platformos-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up logs directory
        run: |
          mkdir -p ${{ env.LOGS_DIR }}
          chmod -R 777 ${{ env.LOGS_DIR }}

      - name: Start PlatformOS LSP
        id: start_lsp
        run: |
          docker run -i \
            -v ${{ env.DOCKER_WORKSPACE }}:${{ env.DOCKER_WORKSPACE }} \
            -w ${{ env.DOCKER_WORKSPACE }} \
            -e PLATFORMOS_CHECK_DEBUG=${{ env.PLATFORMOS_CHECK_DEBUG }} \
            -e PLATFORMOS_CHECK_DEBUG_LOG_FILE=${{ env.DOCKER_WORKSPACE }}/${{ env.LOGS_DIR }}/platformos-lsp.log \
            platformos/platformos-lsp:latest

      - name: Run platformos-check
        id: run_check
        if: steps.start_lsp.outcome == 'success'
        run: |
          set +e  # Disable exit on error
          docker run -i \
            -v ${{ env.DOCKER_WORKSPACE }}:${{ env.DOCKER_WORKSPACE }} \
            -w ${{ env.DOCKER_WORKSPACE }} \
            -e PLATFORMOS_CHECK_DEBUG=${{ env.PLATFORMOS_CHECK_DEBUG }} \
            -e PLATFORMOS_CHECK_DEBUG_LOG_FILE=${{ env.DOCKER_WORKSPACE }}/${{ env.LOGS_DIR }}/platformos-check.log \
            platformos/platformos-check:latest -o json > ${{ env.LOGS_DIR }}/platformos-check-raw.json
          docker_exit_code=$?
          set -e  # Re-enable exit on error

          jq . ${{ env.LOGS_DIR }}/platformos-check-raw.json | tee ${{ env.LOGS_DIR }}/platformos-check.json

          exit $docker_exit_code

      - name: Upload logs
        if: always() && steps.run_check.outcome != 'skipped'
        uses: actions/upload-artifact@v4
        with:
          name: platformos_check_logs_${{ github.run_id }}
          path: |
            ${{ env.LOGS_DIR }}/platformos-lsp.log
            ${{ env.LOGS_DIR }}/platformos-check.json
            ${{ env.LOGS_DIR }}/platformos-check-raw.json

      - name: Generate summary
        if: always() && steps.run_check.outcome != 'skipped'
        run: |
          echo "# PlatformOS Check Summary :checkered_flag:" >> $GITHUB_STEP_SUMMARY
          echo "## Result: ${{ steps.run_check.outcome }} ${{ env.RESULT_ICON }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ -f "${{ env.LOGS_DIR }}/platformos-check.json" ]; then
            echo "## Issues Found" >> $GITHUB_STEP_SUMMARY
            echo "| File | Line | Column | Severity | Check | Message |" >> $GITHUB_STEP_SUMMARY
            echo "|------|------|--------|----------|-------|---------|" >> $GITHUB_STEP_SUMMARY
            jq -r '.[] | .path as $file | .offenses[] | "| \($file) | \(.start_row) | \(.start_column) | \(.severity) | \(.check) | \(.message) |"' ${{ env.LOGS_DIR }}/platformos-check.json >> $GITHUB_STEP_SUMMARY 2>/dev/null || echo "| N/A | N/A | N/A | N/A | N/A | Failed to parse JSON output |" >> $GITHUB_STEP_SUMMARY
          else
            echo "## No output file found" >> $GITHUB_STEP_SUMMARY
          fi
        env:
          RESULT_ICON: ${{ steps.run_check.outcome == 'success' && ':white_check_mark:' || ':x:' }}

      - name: Fail job if platformos-check failed
        if: always() && steps.run_check.outcome == 'failure'
        run: |
          echo "platformos-check failed — marking job as failed"
          exit 1

