name: Capture base screenshots

on:
  workflow_call:
    inputs:
      base-branch-for-capturing:
        required: true
        type: string
      docker-image-for-capture:
        description: 'Docker image to be used when capturing screenshots'
        required: true
        type: string

jobs:
  reserve-ci-instance:
    runs-on: ubuntu-latest
    container: alpine:3.15
    outputs:
      mpkit-url: ${{ steps.reserve.outputs.mpkit-url }}
      report-path: ${{ steps.reserve.outputs.report-path }}
    steps:
      - name: Get ci-instance-url
        id: reserve
        uses: Platform-OS/ci-repository-reserve-instance-url@0.0.9
        with:
          repository-url: https://ci-repository.staging.oregon.platform-os.com
          method: reserve
          pos-ci-repo-token: ${{ secrets.POS_CI_REPO_ACCESS_TOKEN }}

  #call-build-and-deploy-workflow-for-dcra-projects:
  #  if: ${{ github.repository != 'Platform-OS/marketplace-dcra' }}
  #  needs: ["reserve-ci-instance"]
  #  uses: ./.github/workflows/deploy_dcra_market.yml
  #  secrets: inherit
  #  with:
  #    MPKIT_URL: ${{ needs.reserve-ci-instance.outputs.mpkit-url }}

  call-build-and-deploy-workflow-for-dcra-marketplace:
    if: ${{ github.repository == 'Platform-OS/marketplace-dcra' }}
    needs: ["reserve-ci-instance"]
    uses: ./.github/workflows/deploy_dcra_market.yml
    secrets: inherit
    with:
      MPKIT_URL: ${{ needs.reserve-ci-instance.outputs.mpkit-url }}

  capture:
    needs: ["reserve-ci-instance", "call-build-and-deploy-workflow-for-dcra-marketplace"]
    if: ${{ success() }}
    runs-on: ubuntu-latest
    container: ${{ inputs.docker-image-for-capture }}
    timeout-minutes: 35
    strategy:
      max-parallel: 1
      matrix:
        resolution: ["desktop", "mobile"]
    env:
      MPKIT_EMAIL: ${{ secrets.MPKIT_EMAIL }}
      MPKIT_TOKEN: ${{ secrets.MPKIT_TOKEN }}
      MPKIT_URL: ${{ needs.reserve-ci-instance.outputs.mpkit-url }}
      CI: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Install test dependencies
        run: |
          npm install --prefix tests
        shell: sh

      - uses: Platform-OS/gh-action-run-tc-blink-diff-capture-base-snapshots@gh-artifacts
        name: Capture base screenshots for ${{ matrix.resolution }} resolution
        if: success()
        with:
          base: ${{ inputs.base-branch-for-capturing }}
          npm-prefix: tests
          resolution: ${{ matrix.resolution }}
          test-name: tc-${{ matrix.resolution }}-snapshots-capture

  cleanup:
    if: ${{ always() }}
    needs: ["reserve-ci-instance", "capture"]
    runs-on: ubuntu-latest
    container: alpine:3.15
    steps:
      - name: release ci-instance-url
        uses: Platform-OS/ci-repository-reserve-instance-url@0.0.9
        with:
          method: release
          repository-url: https://ci-repository.staging.oregon.platform-os.com
          pos-ci-repo-token: ${{ secrets.POS_CI_REPO_ACCESS_TOKEN }}
