name: Compare screenshots

on:
  workflow_call:
    inputs:
      docker_image_for_compare:
        description: "Docker image to be used when running the compare job"
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #pre_job:
  #  # continue-on-error: true # Uncomment once integration is finished
  #  runs-on: ubuntu-latest
  #  # Map a step output to a job output
  #  outputs:
  #    should_skip: ${{ steps.skip_check.outputs.should_skip }}
  #  steps:
  #    - id: skip_check
  #      uses: fkirc/skip-duplicate-actions@master
  #      with:
  #        github_token: ${{ github.token }}
  #        paths_ignore: '["**/README.md"]'
  #        do_not_skip: '["push"]'

  reserve-ci-instance:
    #needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    container: alpine:3.15
    outputs:
      mpkit-url: ${{ steps.reserve.outputs.mpkit-url }}
      report-path: ${{ steps.reserve.outputs.report-path }}
    steps:
      - name: Get ci-instance-url
        id: reserve
        uses: Platform-OS/ci-repository-reserve-instance-url@0.0.9
        with:
          repository-url: https://ci-repository.staging.oregon.platform-os.com
          method: reserve
          pos-ci-repo-token: ${{ secrets.POS_CI_REPO_ACCESS_TOKEN }}

  deploy:
    needs: ["reserve-ci-instance"]
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      MPKIT_URL: ${{ needs.reserve-ci-instance.outputs.mpkit-url }}
      MPKIT_EMAIL: ${{ secrets.MPKIT_EMAIL }}
      MPKIT_TOKEN: ${{ secrets.MPKIT_TOKEN }}
      CI: false
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      DEBUG: 1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            front_app/node_modules
          key: cache-node-modules-${{ hashFiles('front_app/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm run install:ci

      - name: Set SHA
        run: |
          echo "::set-env name=FRONT_APP_SHA::$( git rev-list -1 HEAD -- front_app )"
        shell: bash

      - name: Cache front_app Assets
        id: cache-front_app-assets
        uses: actions/cache@v2
        with:
          path: |
            app/assets/app
            app/views/layouts/app.liquid
          key: ${{env.MPKIT_URL}}-front_app-assets-${{ env.FRONT_APP_SHA }}

      - name: Build front_app
        if: steps.cache-front_app-assets.outputs.cache-hit != 'true'
        env:
          PUBLIC_URL: "${{ env.MPKIT_URL}}/assets/app/"
          REACT_APP_API_URL: "${{env.MPKIT_URL}}/api"
        shell: sh
        run: |
          echo "-----------------------------------------"
          echo $PUBLIC_URL
          echo $REACT_APP_API_URL
          echo "-----------------------------------------"
          npm run --prefix front_app build

      - name: Deploy
        env:
          CI: true
        shell: sh
        run: |
          set -e
          unset DEBUG
          npm -g install @platformos/pos-cli

          sh ./tests/seed.sh

  compare:
    needs: ["reserve-ci-instance", "deploy"]
    runs-on: ubuntu-latest
    container: ${{ inputs.docker_image_for_compare }}
    timeout-minutes: 20
    strategy:
      max-parallel: 1
      matrix:
        resolution: ["desktop", "mobile"]
    outputs:
      desktop-diff-conclusion: ${{ steps.diff-test.outputs.desktop-diff-conclusion }}
      desktop-diff-report-url: ${{ steps.diff-test.outputs.desktop-diff-report-url }}
      mobile-diff-conclusion: ${{ steps.diff-test.outputs.mobile-diff-conclusion }}
      mobile-diff-report-url: ${{ steps.diff-test.outputs.mobile-diff-report-url }}
    env:
      MPKIT_EMAIL: ${{ secrets.MPKIT_EMAIL }}
      MPKIT_TOKEN: ${{ secrets.MPKIT_TOKEN }}
      MPKIT_URL: ${{ needs.reserve-ci-instance.outputs.mpkit-url }}
      UPLOAD_HOST: https://tests.qa0.oregon.platformos.com
      CI: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Install test dependencies
        run: |
          npm install --prefix tests
        shell: sh

      - uses: Platform-OS/gh-action-run-tc-blink-diff@60b8cc2ca6b96359e6ada0c8140eff81136dcd5c
        name: Compare screenshots for ${{ matrix.resolution }} resolution
        id: diff-test
        if: success() || failure()
        with:
          npm-prefix: tests
          test-name: tc-${{ matrix.resolution }}-snapshots-diff
          base: release_candidate
        env:
          resolution: ${{ matrix.resolution }}

  notify:
    needs: ["reserve-ci-instance", "deploy", "compare"]
    if: ${{ success() || failure() }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      CI: true
      MPKIT_EMAIL: ${{ secrets.MPKIT_EMAIL }}
      MPKIT_TOKEN: ${{ secrets.MPKIT_TOKEN }}
      MPKIT_URL: ${{ needs.reserve-ci-instance.outputs.mpkit-url }}
      UPLOAD_HOST: https://tests.qa0.oregon.platformos.com
    steps:

      - name: Send notification to Slack
        id: notify-slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "channel": "test-reports",
              "text": "Visual regression tests",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "testcafe blink diff visual regression tests"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n${{ github.ref_name }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Commit:*\n<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Actor:*\n${{ github.actor }}\n"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View action run>"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                      "text": "${{ env.desktop-result-icon }} <${{ needs.compare.outputs.desktop-diff-report-url }}|View test report for desktop resolution>\n${{ env.mobile-result-icon }} <${{ needs.compare.outputs.mobile-diff-report-url }}|View test report for mobile resolution>\n"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          desktop-result-icon: ${{ needs.compare.outputs.desktop-diff-conclusion == 'success' && ':white_check_mark:' || ':x:' }}
          mobile-result-icon: ${{ needs.compare.outputs.mobile-diff-conclusion == 'success' && ':white_check_mark:' || ':x:' }}

  cleanup:
    if: ${{ always() }}
    needs: ["reserve-ci-instance", "deploy", "compare", "notify"]
    runs-on: ubuntu-latest
    container: alpine:3.15
    steps:
      - name: release ci-instance-url
        uses: Platform-OS/ci-repository-reserve-instance-url@0.0.9
        with:
          method: release
          repository-url: https://ci-repository.staging.oregon.platform-os.com
          pos-ci-repo-token: ${{ secrets.POS_CI_REPO_ACCESS_TOKEN }}
